services:
  dev:
    image: node:22
    working_dir: /neoninja
    container_name: neoninja
    volumes:
      - .:/neoninja
      - /neoninja/node_modules
      - /neoninja/packages/base-ui/node_modules
      - /neoninja/packages/demo/node_modules
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev"
